### PR TITLE
Refactor/input specific settings

### PR DESCRIPTION
**Pull request by rodrigo-ceccato**
Addresses issue #17

### CODE REVIEW

**Comment by cl3to** [comment]
Now, can spinner handle any benchmark command line?

**Comment by rodrigo-ceccato** [comment]
> Now, can spinner handle any benchmark command line?

Yes, it should accept any template as input;

**Comment by cl3to** [comment]
Is this PR ready for review?

**Comment by rodrigo-ceccato** [comment]
Yes it is

**Review by cl3to — APPROVED** [review]
LG

**Pull request merged**
